# Generated by Django 2.2.2 on 2019-07-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareRes', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='category_id',
            new_name='category',
        ),
    ]
